#!/usr/bin/env python3
"""A registry that answers the way minicompiler/mc-registry answers.

Usage: stub.py PORT

It plays the two routes the action uses -- `POST /poll` and `GET /jobs/<id>` --
and the one address it reads the proof from, `GET /index/<name>.toml`. Which
road a request takes is decided by the REPOSITORY in the posted `git_url`, so
one server plays all of them:

  o/good      202, then queued -> running -> done, and the index carries 1.2.0
  o/bad       202, then queued -> failed, with a sandbox refusal in the report
  o/missing   404 `not registered`
  o/busy      429 with `Retry-After: 1` once, then the good road
  o/slow      202, and the job stays queued for ever (the timeout road)
  o/noindex   202, then done -- but the index does not carry the version
  o/theirs    registered to ANOTHER account: 403 with a token, 202 without one
  o/accept    the token's account has a document to accept: 403 `accept ...`

And the token roads of S7 (the registry's web/token.mc): every `POST /poll`
records its `Authorization` header in this server's own log (stderr), which is
where the gate reads what the action sent. With no header the poll is anonymous
and takes the road above; with one, the value decides -- TOKEN_GOOD is the
account that owns `o/good` (202), TOKEN_OTHER is an account that owns nothing
here (403), and anything else is 401 with `WWW-Authenticate: Bearer`, the one
answer the registry gives a revoked, expired or malformed token.

The bodies and the headers are the ones web/repos.mc writes: `queued` with a
`Location`, the three header lines and a blank one before the report, and
`Retry-After: 5` while a job is queued or running. The report of `o/bad`
contains what the registry's own filter would have left behind (`?[31m`), so the
action is proved not to add an escape of its own.
"""

import http.server
import sys
import urllib.parse

PORT = int(sys.argv[1])

# job id -> [repository, [the states it answers, in order]]
JOBS = {}
SEEN = {}                                    # repository -> how many POSTs

REPORT_OK = "clone 180 KiB\nmc pkg hash ok\nbox: ok\npublished 1.2.0\n"
# The report of `o/bad` also carries three GitHub workflow commands at the
# start of a line. A registry that filtered them would not send them; this one
# does, because the action must not depend on that -- `::` at column 0 of the
# runner's stdout is parsed by Actions itself, so `::stop-commands::` there
# would switch the rest of the log into data and `::error::` would raise an
# annotation nobody wrote (the review of the registry's PR #6).
REPORT_BAD = ("clone 180 KiB\n\tindented\n"
              "sandbox: refused: open /etc/shadow\n"
              "colour: ?[31mred?[0m\n"
              "::error::pwned\n"
              "::set-output name=x::y\n"
              "::stop-commands::tok\n")

INDEX_OK = ('# generated by the mc registry\nname = "good"\n\n'
            '[[version]]\nversion = "1.2.0"\n'
            'url = "https://github.com/o/good/archive/refs/tags/v1.2.0.tar.gz"\n')
INDEX_NOVER = ('# generated by the mc registry\nname = "noindex"\n\n'
               '[[version]]\nversion = "1.1.0"\n')

# The three tokens the gate uses, in the registry's shape: `mcr_` + 43 characters
# of base64url. They are fixtures of a loopback server, not credentials.
# test/run.sh reads the two literals out of this file, so they are spelled out.
TOKEN_GOOD = "mcr_ggggggggggggggggggggood-token_0123456789ABC"
TOKEN_OTHER = "mcr_oooooooooooooooooooother-token_0123456789AB"

ROADS = {
    "good": (1, ["queued", "running", "done"], "good", REPORT_OK),
    "theirs": (7, ["queued", "done"], "good", REPORT_OK),
    "accept": (8, ["queued", "done"], "good", REPORT_OK),
    "bad": (2, ["queued", "failed"], "bad", REPORT_BAD),
    "busy": (4, ["done"], "good", REPORT_OK),
    "slow": (5, ["queued"], "slow", "waiting for a worker\n"),
    "noindex": (6, ["done"], "noindex", REPORT_OK),
}


class Handler(http.server.BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def log_message(self, fmt, *args):
        sys.stderr.write("stub: " + (fmt % args) + "\n")

    def answer(self, status, body, ctype="text/plain; charset=utf-8", extra=None):
        b = body.encode()
        self.send_response(status)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(b)))
        self.send_header("Cache-Control", "no-store")
        for k, v in (extra or {}).items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(b)

    def do_POST(self):
        if self.path != "/poll":
            self.answer(405, "method not allowed\n", extra={"Allow": "GET, HEAD"})
            return
        n = int(self.headers.get("Content-Length", "0"))
        form = urllib.parse.parse_qs(self.rfile.read(n).decode())
        url = (form.get("git_url") or [""])[0]
        # What the action sent, for the gate: the header as it came off the
        # wire, or `none`. The registry asks this BEFORE it parses the body.
        auth = self.headers.get("Authorization")
        sys.stderr.write("stub: POST /poll authorization: %s\n"
                         % (auth if auth is not None else "none"))
        sys.stderr.flush()
        account = None
        if auth is not None:
            scheme, _, value = auth.partition(" ")
            value = value.strip()
            if scheme.lower() == "bearer" and value == TOKEN_GOOD:
                account = "good"
            elif scheme.lower() == "bearer" and value == TOKEN_OTHER:
                account = "other"
            else:
                self.answer(401, "the token is not valid\n",
                            extra={"WWW-Authenticate": "Bearer"})
                return
        if not url.startswith("https://github.com/"):
            self.answer(400, "only public GitHub repositories for now\n")
            return
        repo = url[len("https://github.com/"):].split("/")[-1]
        if repo not in ROADS:
            self.answer(404, "not registered\n")
            return
        if account is not None:
            # a registered repository none of whose rows is this account's
            if account == "other" or repo == "theirs":
                self.answer(403, "the token's account does not own this repository\n")
                return
            if repo == "accept":
                self.answer(403, "accept the updated terms first\n")
                return
        SEEN[repo] = SEEN.get(repo, 0) + 1
        if repo == "busy" and SEEN[repo] == 1:
            self.answer(429, "429\n", ctype="text/html; charset=utf-8",
                        extra={"Retry-After": "1"})
            return
        jid, states, package, report = ROADS[repo]
        JOBS.setdefault(jid, {"i": 0, "states": states, "package": package,
                              "report": report})
        self.answer(202, "queued\n", extra={"Location": "/jobs/%d" % jid})

    def do_GET(self):
        if self.path.startswith("/jobs/"):
            self.job(self.path[len("/jobs/"):])
            return
        if self.path.startswith("/index/") and self.path.endswith(".toml"):
            name = self.path[len("/index/"):-len(".toml")]
            if name == "good":
                self.answer(200, INDEX_OK)
            elif name == "noindex":
                self.answer(200, INDEX_NOVER)
            else:
                self.answer(404, "not found\n")
            return
        if self.path == "/poll":
            self.answer(405, "method not allowed\n", extra={"Allow": "POST"})
            return
        self.answer(404, "not found\n")

    def job(self, ids):
        try:
            jid = int(ids)
        except ValueError:
            self.answer(404, "not found\n")
            return
        j = JOBS.get(jid)
        if j is None:
            self.answer(404, "not found\n")
            return
        # each read advances the job by one state, and the last one sticks
        state = j["states"][min(j["i"], len(j["states"]) - 1)]
        j["i"] += 1
        body = "state: %s\nkind: poll\npackage: %s\n\n%s" % (state, j["package"],
                                                             j["report"])
        extra = {}
        if state in ("queued", "running"):
            extra["Retry-After"] = "1"
        self.answer(200, body, extra=extra)


if __name__ == "__main__":
    srv = http.server.ThreadingHTTPServer(("127.0.0.1", PORT), Handler)
    sys.stderr.write("stub: listening on 127.0.0.1:%d\n" % PORT)
    sys.stderr.flush()
    srv.serve_forever()
